target: CD64
registration: DAPI

otsu_segmentation:
  contrast:
    percentile:
      - 0.1
      - 99.9
  tophat:
    element_size:
      - 50
      - 50
  otsu_threshold:
    factor: 2.1
  small_objects:
    min_size: 3.2 # μm²
    connectivity: 2

dapi_segmentation:
  model_name: default # default or model name
  model_diameter: default # default or float for the custom model
  gpu: True

colocalization:
  distance_filter_threshold: 2.25 # μm