name: immune_gpu
channels:
  - bioconda
  - conda-forge
  - cf-staging
  - pytorch
  - nvidia
dependencies:
  - aicsimageio=4.10.0
  - cellpose=2.0.5
  - networkx=3.2.1
  - numpy=1.26.0
  - pandas=2.2.2
  - pulp=2.7.0
  - pyarrow=16.1.0
  - python=3.9.18
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - scikit-image=0.22.0
  - snakemake=7.32.4
  - openpyxl=3.1.2
  - pip:
      - mmv_im2im==0.5.2
      - pydantic==1.*
