name: env
channels:
  - bioconda
  - conda-forge
  - cf-staging
dependencies:
  - aicsimageio=4.9.4
  - numpy=1.21.2
  - pip
  - python=3.9.10
  - pyyaml=6.0
  - scikit-image=0.19.3
  - snakemake=7.24.0
