name: env
channels:
  - bioconda
  - conda-forge
  - cf-staging
dependencies:
  - aicsimageio=4.10.0 #4.9.4
  - cellpose=2.0.5
  - numpy=1.21.2
  - pip
  - porespy=2.3.0
  - python=3.9.10
  - pyyaml=6.0
  - scikit-image=0.19.3
  - snakemake=7.24.0
  - xmlschema=2.3.0
  - pip:
      - mmv_im2im==0.5.1
      - pydantic==1.*
