checkpoint: null
criterion:
  func_name: GeneralizedDiceFocalLoss
  module_name: monai.losses
  params:
    focal_weight:
    - 1.0
    - 10.0
    softmax: true
    to_onehot_y: true
framework: FCN
model_extra:
  pre-train: /mnt/eternus/users/Shuo/project/Robin_task/TMEM119_TASK/lightning_logs/version_1/checkpoints/best.ckpt
net:
  func_name: HighResNet
  module_name: monai.networks.nets
  params:
    in_channels: 1
    out_channels: 2
    spatial_dims: 2
optimizer:
  func_name: AdamW
  module_name: torch.optim
  params:
    lr: 0.0001
    weight_decay: 0.0005
scheduler:
  func_name: ExponentialLR
  module_name: torch.optim.lr_scheduler
  params:
    gamma: 0.99
