### image Channels ###
target:
  # Target cell marker channels, fill in all channel names to use for analysis
  - CD64
registration: DAPI # Channel name of the DAPI marker

### Top Hat ###
top_hat:
  contrast:
    percentile:
      # min and max values to use for contrast stretching
      - 0.1
      - 99.9
  tophat:
    element_size:
      # x and y sizes of the ellipse for the white top hat filter.
      - 16.25
      - 16.25

### Segmentation ###
dapi_segmentation:
  # default or model name for custom cellpose model
  model_name: default
  # default or float for the custom model; if 0, it tries to retrieve it from the model
  model_diameter: 0
  gpu: True

ml_segmentation:
  active: True
  # Example input definition for target cell marker x19
  #x19:
  #  model_name: x19_model <- folder name of the ml model
  #  cutoff_value: 0.1
  CD64:
    model_name: default
    cutoff_value: 0.1
  large_objects:
    # Removes larger objects than max_size after segmentation
    active: True # Default False
    max_size: 600 # μm²
    connectivity: 2
  small_holes:
    # Closes smaller holes than area_threshold after segmentation
    active: True # Default True
    area_threshold: 2.25 # μm²
    connectivity: 1
  small_objects:
    # Removes smaller objects than min_size after segmentation
    active: True # Default True
    min_size: 4 # μm²
    connectivity: 2 # 2
  gpu: True

otsu_segmentation:
  active: False
  otsu_threshold:
    factor: 2.1
  small_objects:
    # Removes smaller objects than min_size after segmentation
    min_size: 3.2 # μm²
    connectivity: 2

### Registration ###
colocalization:
  distance_filter_threshold: 2.25 # μm

### Analyis ###
nearest_neighbor:
  distances:
    - 5
    - 10
    - 20
    - 30
    - 40
# connectivity guide:
#1-connectivity     2-connectivity     diagonal connection close-up
#     [ ]           [ ]  [ ]  [ ]             [ ]
#      |               \  |  /                 |  <- hop 2
#[ ]--[x]--[ ]      [ ]--[x]--[ ]        [x]--[ ]
#      |               /  |  \             hop 1
#     [ ]           [ ]  [ ]  [ ]
