############   config   ############
from os.path import join

PATH = "/home/user/immun_analysis"
INPUT = join(PATH, "input")
OUTPUT = join(PATH, "result")
CONFIG = "config.yaml"
TYPE = (".tif", ".tiff")
image = list(image for image in os.listdir(INPUT) if image.endswith(TYPE))

STEP1 = "otsu_segmented"
TOPHAT = "otsu_tophat"
DAPI = "dapi_segmented"
STEP2 = "otsu_registrated"
DAPIDILATE = "dapi_dilated"
STEP3 = "ml_segmented"
STEP4 = "ml_registrated"


configfile: join(PATH, CONFIG)


############   rules   ############
include: "rules/otsu.smk"
include: "rules/dapi.smk"
include: "rules/registration.smk"
include: "rules/ml.smk"
include: "rules/skeletonization.smk"
include: "rules/statistic.smk"


############   inputs   ############
def get_input(image, input_list=[]):
    input_list.append(expand(join(OUTPUT, STEP1, "{image}"), image=image))
    input_list.append(expand(join(OUTPUT, STEP2, "{image}"), image=image))
    return input_list


############   target rule   ############
rule summary:
    input:
        get_input(image),
