############   config   ############
from os.path import join
TYPE = ".tif"
PATH = "/home/user/immune_analysis"
CONFIG = "config.yaml"
configfile: join(PATH, CONFIG)
INPUT = join(PATH, "input")
OUTPUT = join(PATH, "result")

STEP1 = "otsu_segmented"
STEP2 = "otsu_registrated"
STEP3 = "ml_segmented"
STEP4 = "ml_registrated"

TARGET = "_" + config["target"]
REGISTRATION = "_" + config["registration"]

image = list(set(
    "_".join(image.split("_")[:-1])
    for image in os.listdir(INPUT)
    if image.endswith(TYPE)
))


############   rules   ############
include: "rules/otsu.smk"
include: "rules/registration.smk"
include: "rules/ml.smk"
include: "rules/skeletonization.smk"
include: "rules/statistic.smk"


############   input assembler   ############
def get_input(image, input_list=[]):
    input_list.append(
        expand(join(OUTPUT, STEP1, "{image}" + TYPE), image=image)
    )
    input_list.append(
        expand(join(OUTPUT, STEP2, "{image}" + TYPE), image=image)
    )
    return input_list


############   target rule   ############
rule summary:
    input:
        get_input(image),
